/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlaundry;

import javax.swing.JOptionPane;
import static projectlaundry.LaundryPage.nama;
/**
 *
 * @author Galih
 */
public class Kiloan extends javax.swing.JFrame {

    /**
     * Creates new form Kiloan
     */
    public Kiloan() {
        initComponents();
        txHarga.setEditable(false);

       
    }
    int hasil,bill,bayar,total;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txBerat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txHarga = new javax.swing.JTextField();
        cbService = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        btBatal = new javax.swing.JButton();
        btBayar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kiloan Page");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("KILOAN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(131, 20, 86, 32);

        txBerat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txBerat.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txBeratInputMethodTextChanged(evt);
            }
        });
        txBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txBeratActionPerformed(evt);
            }
        });
        jPanel1.add(txBerat);
        txBerat.setBounds(160, 101, 83, 25);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("BERAT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 46, 20);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Kilogram");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(245, 100, 55, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("HARGA");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 130, 60, 20);

        txHarga.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txHargaActionPerformed(evt);
            }
        });
        jPanel1.add(txHarga);
        txHarga.setBounds(160, 130, 140, 25);

        cbService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Biasa", "Express" }));
        cbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbServiceActionPerformed(evt);
            }
        });
        jPanel1.add(cbService);
        cbService.setBounds(160, 70, 140, 22);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("SERVICE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 70, 59, 19);

        btBatal.setText("BATAL");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btBatal);
        btBatal.setBounds(50, 170, 70, 25);

        btBayar.setText("BAYAR");
        btBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBayarActionPerformed(evt);
            }
        });
        jPanel1.add(btBayar);
        btBayar.setBounds(230, 170, 71, 25);

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 170, 71, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(370, 287));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txBeratInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txBeratInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txBeratInputMethodTextChanged

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LaundryPage page = new LaundryPage();
        page.setVisible(true);
    }//GEN-LAST:event_btBatalActionPerformed

    private void txBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txBeratActionPerformed
        // TODO add your handling code here:
       int berat = Integer.parseInt(txBerat.getText());
       
       if (cbService.getSelectedItem().equals("Biasa")) {
           total = berat * 7000;
       }
       if (cbService.getSelectedItem().equals("Express")) {
           total = berat * 10000;
       }
       
       String jadi = Integer.toString(total);
       txHarga.setText(jadi);
    }//GEN-LAST:event_txBeratActionPerformed
int x;
    private void btBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBayarActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Apakah Anda Ingin Menggunakan Gopay Untuk Pembayaran Anda? Cashback 30%", 
                    "Gopay Page", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);
        int bayar;
        switch(jawab){
        case JOptionPane.YES_OPTION: 
            int diskon = (total * 30)/100;
            int total1 = total - diskon;
            JOptionPane.showMessageDialog(null, "Total Pembayaran Anda Adalah " + total1 + "\nTerima Kasih, Pak/Ibu " + nama);
            break;
        case JOptionPane.NO_OPTION:
            do {
            String inputan = JOptionPane.showInputDialog("Jumlah Uang Yang Akan Dibayarkan");
            bayar = Integer.parseInt(inputan);
            total1 = bayar - total;
                if (bayar >= total) {
                    x = 1;
                } else if (bayar < total) {
                    JOptionPane.showMessageDialog(null, "Uang Yang Anda Bayarkan Tidak Sesuai, Silahkan Masukan Kembali");
                    x = 0;
                }
            } while( x == 0);    
            if ( bayar == total ) {
                JOptionPane.showMessageDialog(null, "Uang Anda Pas" + "\nTerima Kasih, Pak/Ibu " + nama);
            } 
            else {
            JOptionPane.showMessageDialog(null, "Kembalian Anda Adalah " + total1 + "\nTerima Kasih, Pak/Ibu " + nama);
            break; 
            }
        }
        this.dispose();
    }//GEN-LAST:event_btBayarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txBerat.setText("");
        txHarga.setText("");
        cbService.setSelectedItem("Pilih");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbServiceActionPerformed

    private void txHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiloan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiloan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btBayar;
    private javax.swing.JComboBox<String> cbService;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txBerat;
    private javax.swing.JTextField txHarga;
    // End of variables declaration//GEN-END:variables
}
