 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectlaundry;

import java.lang.reflect.Array;
import javax.swing.JOptionPane;
import static projectlaundry.LaundryPage.nama;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;




/**
 *
 * @author Galih
 */
public class Special2 extends javax.swing.JFrame {
public static int i,j;
String[]  berhasil = new String[100];
    


    /**
     * Creates new form Special2
     */
    DefaultTableModel model;
    public Special2() {

        initComponents();

        tfHarga.setEditable(false);
        
          Object kolom[] = {"No.","Jenis","Harga"};

        Object data [][]={ 
        {"1","Bed Cover Kecil","15000"},
        {"2","Bed Cover Besar","20000"},
        {"3","Bed Cover Jumbo","30000"},
        {"4","Helm","12000"},
        {"5","Handuk","7000"},
        {"6","Jaket","10000"},
        {"7","Selimut Besar","22000"},
        {"8","Selimut Kecil","15000"},
        {"9","Sepatu Kulit","18000"},
        {"10","Sepatu Cat","15000"},
        {"11","Karpet Kecil","30000"},
        {"12","Karpet Sedang","50000"},
        {"13","Karpet Besar","70000"},
        {"14","Karpet Jumbo","90000"},
        {"15","Jas","30000"},
        {"16","Kebaya","20000"},
        {"17","Blezer","20000"},
        {"18","Rompi","10000"},
        {"19","Boneka Kecil","10000"},
        {"20","Boneka Sedang","15000"},
        {"21","Boneka Besar","30000"},
        {"22","Boneka Jumbo","40000"},
        {"23","Gorden Tipis","10000"},
        {"24","Gorden Tebal","15000"},
        {"25","Sprei Kecil","12000"},
        {"26","Sprei Besar","20000"},
        {"27","Keset","20000"},
        {"28","Tas Kecil","15000"},
        {"29","Tas Besar","30000"},
        {"30","Travel Bag","40000"},
        };
        
        
        model = new DefaultTableModel(data, kolom);
        tabel.setModel(model);
        lebarKolom();
    }
    
    public void lebarKolom(){ 
        TableColumn column;
        tabel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = tabel.getColumnModel().getColumn(0); 
        column.setPreferredWidth(30);
        column = tabel.getColumnModel().getColumn(1); 
        column.setPreferredWidth(163); 
        column = tabel.getColumnModel().getColumn(2); 
        column.setPreferredWidth(70); 
    }
    
        int total;
        String bill;
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ckBedcoverKecil = new javax.swing.JCheckBox();
        ckBedcoverBesar = new javax.swing.JCheckBox();
        ckHelm = new javax.swing.JCheckBox();
        ckBedcoverJumbo = new javax.swing.JCheckBox();
        ckJaket = new javax.swing.JCheckBox();
        ckHanduk = new javax.swing.JCheckBox();
        ckSelimutKecil = new javax.swing.JCheckBox();
        ckSelimutBesar = new javax.swing.JCheckBox();
        ckSepatuCat = new javax.swing.JCheckBox();
        ckSepatuKulit = new javax.swing.JCheckBox();
        tfBedcoverBesar = new javax.swing.JTextField();
        tfBedcoverKecil = new javax.swing.JTextField();
        tfHelm = new javax.swing.JTextField();
        tfBedcoverJumbo = new javax.swing.JTextField();
        tfJaket = new javax.swing.JTextField();
        tfHanduk = new javax.swing.JTextField();
        tfSelimutKecil = new javax.swing.JTextField();
        tfSelimutBesar = new javax.swing.JTextField();
        tfSepatuCat = new javax.swing.JTextField();
        tfSepatuKulit = new javax.swing.JTextField();
        ckKarpetKecil = new javax.swing.JCheckBox();
        tfKarpetKecil = new javax.swing.JTextField();
        ckKarpetSedang = new javax.swing.JCheckBox();
        tfKarpetSedang = new javax.swing.JTextField();
        ckKarpetBesar = new javax.swing.JCheckBox();
        tfKarpetBesar = new javax.swing.JTextField();
        ckKarpetJumbo = new javax.swing.JCheckBox();
        tfKarpetJumbo = new javax.swing.JTextField();
        ckJas = new javax.swing.JCheckBox();
        tfJas = new javax.swing.JTextField();
        ckKebaya = new javax.swing.JCheckBox();
        tfKebaya = new javax.swing.JTextField();
        ckBlezer = new javax.swing.JCheckBox();
        tfBlezer = new javax.swing.JTextField();
        ckRompi = new javax.swing.JCheckBox();
        tfRompi = new javax.swing.JTextField();
        ckBonekaKecil = new javax.swing.JCheckBox();
        tfBonekaKecil = new javax.swing.JTextField();
        ckBonekaSedang = new javax.swing.JCheckBox();
        tfBonekaSedang = new javax.swing.JTextField();
        ckBonekaBesar = new javax.swing.JCheckBox();
        tfBonekaBesar = new javax.swing.JTextField();
        ckBonekaJumbo = new javax.swing.JCheckBox();
        tfBonekaJumbo = new javax.swing.JTextField();
        ckGordenTipis = new javax.swing.JCheckBox();
        tfGordenTipis = new javax.swing.JTextField();
        ckGordenTebal = new javax.swing.JCheckBox();
        tfGordenTebal = new javax.swing.JTextField();
        ckSpreiKecil = new javax.swing.JCheckBox();
        tfSpreiKecil = new javax.swing.JTextField();
        ckSpreiBesar = new javax.swing.JCheckBox();
        tfSpreiBesar = new javax.swing.JTextField();
        ckKeset = new javax.swing.JCheckBox();
        tfKeset = new javax.swing.JTextField();
        ckTasKecil = new javax.swing.JCheckBox();
        tfTasKecil = new javax.swing.JTextField();
        ckTasBesar = new javax.swing.JCheckBox();
        tfTasBesar = new javax.swing.JTextField();
        ckTravelBag = new javax.swing.JCheckBox();
        tfTravelBag = new javax.swing.JTextField();
        btHapus = new javax.swing.JButton();
        btHitung = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        btBayar1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Special Page");

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        jLabel1.setText("HARGA");

        ckBedcoverKecil.setBackground(new java.awt.Color(255, 255, 255));
        ckBedcoverKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBedcoverKecil.setText("Bed Cover Kecil");
        ckBedcoverKecil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckBedcoverKecilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ckBedcoverKecilMouseEntered(evt);
            }
        });
        ckBedcoverKecil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckBedcoverKecilActionPerformed(evt);
            }
        });

        ckBedcoverBesar.setBackground(new java.awt.Color(255, 255, 255));
        ckBedcoverBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBedcoverBesar.setText("Bed Cover Besar");

        ckHelm.setBackground(new java.awt.Color(255, 255, 255));
        ckHelm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckHelm.setText("Helm");

        ckBedcoverJumbo.setBackground(new java.awt.Color(255, 255, 255));
        ckBedcoverJumbo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBedcoverJumbo.setText("Bed Cover Jumbo");

        ckJaket.setBackground(new java.awt.Color(255, 255, 255));
        ckJaket.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckJaket.setText("Jaket Kulit");

        ckHanduk.setBackground(new java.awt.Color(255, 255, 255));
        ckHanduk.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckHanduk.setText("Handuk");

        ckSelimutKecil.setBackground(new java.awt.Color(255, 255, 255));
        ckSelimutKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckSelimutKecil.setText("Selimut Kecil");

        ckSelimutBesar.setBackground(new java.awt.Color(255, 255, 255));
        ckSelimutBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckSelimutBesar.setText("Selimut Besar");

        ckSepatuCat.setBackground(new java.awt.Color(255, 255, 255));
        ckSepatuCat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckSepatuCat.setText("Sepatu Cat");

        ckSepatuKulit.setBackground(new java.awt.Color(255, 255, 255));
        ckSepatuKulit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckSepatuKulit.setText("Sepatu Kulit");

        tfBedcoverBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfBedcoverKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfHelm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfBedcoverJumbo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfJaket.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfHanduk.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfSelimutKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfSelimutBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfSepatuCat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfSepatuKulit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckKarpetKecil.setBackground(new java.awt.Color(255, 255, 255));
        ckKarpetKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckKarpetKecil.setText("Karpet Kecil");

        tfKarpetKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckKarpetSedang.setBackground(new java.awt.Color(255, 255, 255));
        ckKarpetSedang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckKarpetSedang.setText("Karpet Sedang");

        tfKarpetSedang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckKarpetBesar.setBackground(new java.awt.Color(255, 255, 255));
        ckKarpetBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckKarpetBesar.setText("Karpet Besar");

        tfKarpetBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckKarpetJumbo.setBackground(new java.awt.Color(255, 255, 255));
        ckKarpetJumbo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckKarpetJumbo.setText("Karpet Jumbo");

        tfKarpetJumbo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckJas.setBackground(new java.awt.Color(255, 255, 255));
        ckJas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckJas.setText("Jas");

        tfJas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckKebaya.setBackground(new java.awt.Color(255, 255, 255));
        ckKebaya.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckKebaya.setText("Kebaya");

        tfKebaya.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckBlezer.setBackground(new java.awt.Color(255, 255, 255));
        ckBlezer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBlezer.setText("Blezer");

        tfBlezer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckRompi.setBackground(new java.awt.Color(255, 255, 255));
        ckRompi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckRompi.setText("Rompi");

        tfRompi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckBonekaKecil.setBackground(new java.awt.Color(255, 255, 255));
        ckBonekaKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBonekaKecil.setText("Boneka Kecil");

        tfBonekaKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckBonekaSedang.setBackground(new java.awt.Color(255, 255, 255));
        ckBonekaSedang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBonekaSedang.setText("Boneka Sedang");

        tfBonekaSedang.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckBonekaBesar.setBackground(new java.awt.Color(255, 255, 255));
        ckBonekaBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBonekaBesar.setText("Boneka Besar");

        tfBonekaBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckBonekaJumbo.setBackground(new java.awt.Color(255, 255, 255));
        ckBonekaJumbo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckBonekaJumbo.setText("Boneka Jumbo");

        tfBonekaJumbo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckGordenTipis.setBackground(new java.awt.Color(255, 255, 255));
        ckGordenTipis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckGordenTipis.setText("Gorden Tipis");

        tfGordenTipis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckGordenTebal.setBackground(new java.awt.Color(255, 255, 255));
        ckGordenTebal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckGordenTebal.setText("Gorden Tebal");

        tfGordenTebal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckSpreiKecil.setBackground(new java.awt.Color(255, 255, 255));
        ckSpreiKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckSpreiKecil.setText("Sprei Kecil");

        tfSpreiKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckSpreiBesar.setBackground(new java.awt.Color(255, 255, 255));
        ckSpreiBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckSpreiBesar.setText("Sprei Besar");

        tfSpreiBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckKeset.setBackground(new java.awt.Color(255, 255, 255));
        ckKeset.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckKeset.setText("Keset");

        tfKeset.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckTasKecil.setBackground(new java.awt.Color(255, 255, 255));
        ckTasKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckTasKecil.setText("Tas Kecil");

        tfTasKecil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckTasBesar.setBackground(new java.awt.Color(255, 255, 255));
        ckTasBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckTasBesar.setText("Tas Besar");

        tfTasBesar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        ckTravelBag.setBackground(new java.awt.Color(255, 255, 255));
        ckTravelBag.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ckTravelBag.setText("Travel Bag");

        tfTravelBag.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btHapus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btHapus.setText("HAPUS");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btHitung.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btHitung.setText("HITUNG");
        btHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHitungActionPerformed(evt);
            }
        });

        btBatal.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btBatal.setText("BATAL");
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        jLabel2.setText("SPECIAL");

        tfHarga.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        tfHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaActionPerformed(evt);
            }
        });

        btBayar1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        btBayar1.setText("BAYAR");
        btBayar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBayar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckBedcoverKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBedcoverKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckKarpetKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfKarpetKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckBonekaBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBonekaBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckBedcoverBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBedcoverBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckKarpetSedang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfKarpetSedang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckBonekaJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBonekaJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckBedcoverJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBedcoverJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckKarpetBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfKarpetBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckGordenTipis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfGordenTipis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckKarpetJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfKarpetJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckGordenTebal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfGordenTebal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckHanduk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfHanduk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckJas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfJas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckSpreiKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSpreiKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckKebaya, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfKebaya, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckSpreiBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSpreiBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckSelimutBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSelimutBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckBlezer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBlezer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckKeset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfKeset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckSelimutKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSelimutKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckRompi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfRompi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckTasKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfTasKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckSepatuKulit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSepatuKulit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckBonekaKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBonekaKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckTasBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfTasBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ckSepatuCat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfSepatuCat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckBonekaSedang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfBonekaSedang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(ckTravelBag, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfTravelBag, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(btBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckBedcoverKecil)
                    .addComponent(tfBedcoverKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKarpetKecil)
                    .addComponent(tfKarpetKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckBonekaBesar)
                    .addComponent(tfBonekaBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckBedcoverBesar)
                    .addComponent(tfBedcoverBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKarpetSedang)
                    .addComponent(tfKarpetSedang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckBonekaJumbo)
                    .addComponent(tfBonekaJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckBedcoverJumbo)
                    .addComponent(tfBedcoverJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKarpetBesar)
                    .addComponent(tfKarpetBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckGordenTipis)
                    .addComponent(tfGordenTipis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckHelm)
                    .addComponent(tfHelm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKarpetJumbo)
                    .addComponent(tfKarpetJumbo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckGordenTebal)
                    .addComponent(tfGordenTebal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckHanduk)
                    .addComponent(tfHanduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckJas)
                    .addComponent(tfJas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckSpreiKecil)
                    .addComponent(tfSpreiKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckJaket)
                    .addComponent(tfJaket, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKebaya)
                    .addComponent(tfKebaya, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckSpreiBesar)
                    .addComponent(tfSpreiBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckSelimutBesar)
                    .addComponent(tfSelimutBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckBlezer)
                    .addComponent(tfBlezer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckKeset)
                    .addComponent(tfKeset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckSelimutKecil)
                    .addComponent(tfSelimutKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckRompi)
                    .addComponent(tfRompi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckTasKecil)
                    .addComponent(tfTasKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckSepatuKulit)
                    .addComponent(tfSepatuKulit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckBonekaKecil)
                    .addComponent(tfBonekaKecil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckTasBesar)
                    .addComponent(tfTasBesar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckSepatuCat)
                    .addComponent(tfSepatuCat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckBonekaSedang)
                    .addComponent(tfBonekaSedang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckTravelBag)
                    .addComponent(tfTravelBag, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(btBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 204, 255));
        jPanel4.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Jenis", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(50, 130, 285, 345);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("LIST HARGA");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(80, 40, 210, 47);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1147, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        // TODO add your handling code here:
    
        this.dispose();
        LaundryPage laundri = new LaundryPage();
        laundri.setVisible(true);
    }//GEN-LAST:event_btBatalActionPerformed

    private void ckBedcoverKecilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckBedcoverKecilMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_ckBedcoverKecilMouseEntered

    private void ckBedcoverKecilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckBedcoverKecilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ckBedcoverKecilMouseClicked

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        // TODO add your handling code here:
         for ( int i = 0 ; i < berhasil.length ; i++ ) {
            berhasil[i] = " " ;
            }
        total = 0;
        ckBedcoverBesar.setSelected(false);
        ckBedcoverJumbo.setSelected(false);
        ckBedcoverKecil.setSelected(false);
        ckBlezer.setSelected(false);
        ckBonekaBesar.setSelected(false);
        ckBonekaJumbo.setSelected(false);
        ckBonekaKecil.setSelected(false);
        ckBonekaSedang.setSelected(false);
        ckGordenTebal.setSelected(false);
        ckGordenTipis.setSelected(false);
        ckHanduk.setSelected(false);
        ckHelm.setSelected(false);
        ckJaket.setSelected(false);
        ckJas.setSelected(false);
        ckKarpetBesar.setSelected(false);
        ckKarpetJumbo.setSelected(false);
        ckKarpetKecil.setSelected(false);
        ckKarpetSedang.setSelected(false);
        ckKebaya.setSelected(false);
        ckKeset.setSelected(false);
        ckRompi.setSelected(false);
        ckSelimutBesar.setSelected(false);
        ckSelimutKecil.setSelected(false);
        ckSepatuKulit.setSelected(false);
        ckSepatuCat.setSelected(false);
        ckSpreiBesar.setSelected(false);
        ckSpreiKecil.setSelected(false);
        ckTasBesar.setSelected(false);
        ckTasKecil.setSelected(false);
        ckTravelBag.setSelected(false);

        tfBedcoverBesar.setText("");
        tfBedcoverJumbo.setText("");
        tfBedcoverKecil.setText("");
        tfBlezer.setText("");
        tfBonekaBesar.setText("");
        tfBonekaJumbo.setText("");
        tfBonekaKecil.setText("");
        tfBonekaSedang.setText("");
        tfGordenTebal.setText("");
        tfGordenTipis.setText("");
        tfHanduk.setText("");
        tfHelm.setText("");
        tfJaket.setText("");
        tfJas.setText("");
        tfKarpetBesar.setText("");
        tfKarpetJumbo.setText("");
        tfKarpetKecil.setText("");
        tfKarpetSedang.setText("");
        tfKebaya.setText("");
        tfKeset.setText("");
        tfRompi.setText("");
        tfSelimutBesar.setText("");
        tfSelimutKecil.setText("");
        tfSepatuKulit.setText("");
        tfSepatuCat.setText("");
        tfSpreiBesar.setText("");
        tfSpreiKecil.setText("");
        tfTasBesar.setText("");
        tfTasKecil.setText("");
        tfTravelBag.setText("");
        tfHarga.setText("");
    }//GEN-LAST:event_btHapusActionPerformed

    private void btHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHitungActionPerformed

      
// TODO add your handling code here:
            for ( int i = 0 ; i < berhasil.length ; i++ ) {
            berhasil[i] = " " ;
            }
            
            total = 0;
            if (ckBedcoverKecil.isSelected()) {
            int bil = Integer.parseInt(tfBedcoverKecil.getText());
            int total1 = (bil * 15000) + total;
            total = total1;
            bill = Integer.toString(total1);
        
            for ( i = 0    ; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Bed Cover Kecil          @Rp 15.000                   "+bil;
                    j=i +1;
                    
                }
              break;
            }
            }
            
            
            if (ckBedcoverBesar.isSelected()) {
            int bil = Integer.parseInt(tfBedcoverBesar.getText());
            int total1 = (bil * 20000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
                    
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Bed Cover Besar        @Rp 20.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckBedcoverJumbo.isSelected()) {
            int bil = Integer.parseInt(tfBedcoverJumbo.getText());
            int total1 = (bil * 30000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Bed Cover Jumbo       @Rp 30.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            
            }
            if (ckBlezer.isSelected()) {
            int bil = Integer.parseInt(tfBlezer.getText());
            int total1 = (bil * 20000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Blazer                            @Rp 20.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
           
            }
            if (ckBonekaBesar.isSelected()) {
            int bil = Integer.parseInt(tfBonekaBesar.getText());
            int total1 = (bil * 30000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Boneka besar             @Rp 30.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckBonekaJumbo.isSelected()) {
            int bil = Integer.parseInt(tfBonekaJumbo.getText());
            int total1 = (bil * 40000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Boneka jumbo            @Rp 40.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckBonekaKecil.isSelected()) {
            int bil = Integer.parseInt(tfBonekaKecil.getText());
            int total1 = (bil * 10000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Boneka kecil                @Rp 10.000                   "+bil;
                    j = i +1; 
                    
                }
                break;
            }
            }
            if (ckBonekaSedang.isSelected()) {
            int bil = Integer.parseInt(tfBonekaSedang.getText());
            int total1 = (bil * 15000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Boneka sedang          @Rp 15.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckGordenTebal.isSelected()) {
            int bil = Integer.parseInt(tfGordenTebal.getText());
            int total1 = (bil * 15000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Gorden Tebel              @Rp 15.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckGordenTipis.isSelected()) {
            int bil = Integer.parseInt(tfGordenTipis.getText());
            int total1 = (bil * 10000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Gorden tipis                 @Rp 10.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckHanduk.isSelected()) {
            int bil = Integer.parseInt(tfHanduk.getText());
            int total1 = (bil * 7000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Handuk                         @Rp 7.000                     "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckHelm.isSelected()) {
            int bil = Integer.parseInt(tfHelm.getText());
            int total1 = (bil * 12000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Helm                             @Rp 12.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckJaket.isSelected()) {
            int bil = Integer.parseInt(tfJaket.getText());
            int total1 = (bil * 10000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Jaket                              @Rp 10.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckJas.isSelected()) {
            int bil = Integer.parseInt(tfJas.getText());
            int total1 = (bil * 30000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Jas                                 @Rp 30.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckKarpetBesar.isSelected()) {
            int bil = Integer.parseInt(tfKarpetBesar.getText());
            int total1 = (bil * 70000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Karpet besar                @Rp 70.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckKarpetJumbo.isSelected()) {
            int bil = Integer.parseInt(tfKarpetJumbo.getText());
            int total1 = (bil * 90000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Karpet jumbo               @Rp 90.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckKarpetKecil.isSelected()) {
            int bil = Integer.parseInt(tfKarpetKecil.getText());
            int total1 = (bil * 30000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Karpet kecil                  @Rp 30.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckKarpetSedang.isSelected()) {
            int bil = Integer.parseInt(tfKarpetSedang.getText());
            int total1 = (bil * 50000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Karpet sedang            @Rp 50.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckKebaya.isSelected()) {
            int bil = Integer.parseInt(tfKebaya.getText());
            int total1 = (bil * 20000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Kebaya                          @Rp 20.000                   "+bil;
                    j = i +1;   
                    
                }
                break;
            }
            }
            if (ckKeset.isSelected()) {
            int bil = Integer.parseInt(tfKeset.getText());
            int total1 = (bil * 20000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Keset                            @Rp 20.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckRompi.isSelected()) {
            int bil = Integer.parseInt(tfRompi.getText());
            int total1 = (bil * 10000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Rompi                           @Rp 10.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckSelimutBesar.isSelected()) {
            int bil = Integer.parseInt(tfSelimutBesar.getText());
            int total1 = (bil * 22000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Selimut besar              @RP 22.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckSelimutKecil.isSelected()) {
            int bil = Integer.parseInt(tfSelimutKecil.getText());
            int total1 = (bil * 15000) + total;
            total = total1;
            bill = Integer.toString(total1);
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Selimut kecil                @Rp 15.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckSepatuCat.isSelected()) {
            int bil = Integer.parseInt(tfSepatuCat.getText());
            int total1 = (bil * 15000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Sepatu cat                    @Rp 15.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckSepatuKulit.isSelected()) {
            int bil = Integer.parseInt(tfSepatuKulit.getText());
            int total1 = (bil * 18000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Sepatu kulit                  @Rp 18.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckSpreiBesar.isSelected()) {
            int bil = Integer.parseInt(tfSpreiBesar.getText());
            int total1 = (bil * 20000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Sprei besar                  @Rp 20.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckSpreiKecil.isSelected()) {
            int bil = Integer.parseInt(tfSpreiKecil.getText());
            int total1 = (bil * 12000) + total;
            total = total1;
            bill = Integer.toString(total1);
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Sprei kecil                    @Rp 12.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckTasBesar.isSelected()) {
            int bil = Integer.parseInt(tfTasBesar.getText());
            int total1 = (bil * 30000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Tas Besar                    @Rp 30.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckTasKecil.isSelected()) {
            int bil = Integer.parseInt(tfTasKecil.getText());
            int total1 = (bil * 15000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Tas kecil                       @Rp 15.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            if (ckTravelBag.isSelected()) {
            int bil = Integer.parseInt(tfTravelBag.getText());
            int total1 = (bil * 40000) + total;
            total = total1;
            bill = Integer.toString(total1);
            
            for ( i= j; i < berhasil.length; i ++ ) {
                if (berhasil[i].equals(" ")) {
                    berhasil[i]= "Travel bag                    @Rp 40.000                   "+bil;
                    j = i +1;
                    
                }
                break;
            }
            }
            tfHarga.setText(bill);
            
    }//GEN-LAST:event_btHitungActionPerformed
    int x;
    private void btBayar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBayar1ActionPerformed

// TODO add your handling code here:
String b = "" ;
        for (int i = 0; i < berhasil.length; i++) {
            
            for ( int x = 0 ; x < 1; x ++){
                if (!berhasil[i].equals(" ")){
                b = b + berhasil[i];
                b = b + "\n";
                break; 
               }
            
            }
            System.out.println(" ");
             
        }
        
           
            JOptionPane.showMessageDialog(this,"NOTA PEMBELIAN\n" + "Nama : " + nama + "\n\nRincian:\n" + b + 
                    "\n====================================" + "\n                                                  TOTAL   =   " + total);
            
        int jawab = JOptionPane.showOptionDialog(this, 
                    "Apakah Anda Ingin Menggunakan Gopay Untuk Pembayaran Anda? Cashback 30%", 
                    "Gopay Page", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE, null, null, null);        
        int bayar;
        switch(jawab){
        case JOptionPane.YES_OPTION: 
            int diskon = (total * 30)/100;
            int total1 = total - diskon;
            JOptionPane.showMessageDialog(null, "Total Pembayaran Anda Adalah " + total1 + "\nTerima Kasih, Pak/Ibu " +nama);
            break;
        case JOptionPane.NO_OPTION:
            do {
            String inputan = JOptionPane.showInputDialog("Jumlah Uang Yang Akan Dibayarkan");
            bayar = Integer.parseInt(inputan);
            total1 = bayar - total;
                if (bayar >= total) {
                    x = 1;
                } else if (bayar < total) {
                    JOptionPane.showMessageDialog(null, "Uang Yang Anda Bayarkan Tidak Sesuai, Silahkan Masukan Kembali");
                    x = 0;
                }
            } while( x == 0);
            if ( bayar == total ) {
                JOptionPane.showMessageDialog(null, "Uang Anda Pas" + "\nTerima Kasih, Pak/Ibu " + nama);
            } 
            else {
            JOptionPane.showMessageDialog(null, "Kembalian Anda Adalah " + total1 + "\nTerima Kasih, Pak/Ibu " + nama);
            break; 
            }
        }
        this.dispose();
    }//GEN-LAST:event_btBayar1ActionPerformed

    private void tfHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaActionPerformed

    private void ckBedcoverKecilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckBedcoverKecilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckBedcoverKecilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Special2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Special2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Special2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Special2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Special2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btBayar1;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btHitung;
    private javax.swing.JCheckBox ckBedcoverBesar;
    private javax.swing.JCheckBox ckBedcoverJumbo;
    private javax.swing.JCheckBox ckBedcoverKecil;
    private javax.swing.JCheckBox ckBlezer;
    private javax.swing.JCheckBox ckBonekaBesar;
    private javax.swing.JCheckBox ckBonekaJumbo;
    private javax.swing.JCheckBox ckBonekaKecil;
    private javax.swing.JCheckBox ckBonekaSedang;
    private javax.swing.JCheckBox ckGordenTebal;
    private javax.swing.JCheckBox ckGordenTipis;
    private javax.swing.JCheckBox ckHanduk;
    private javax.swing.JCheckBox ckHelm;
    private javax.swing.JCheckBox ckJaket;
    private javax.swing.JCheckBox ckJas;
    private javax.swing.JCheckBox ckKarpetBesar;
    private javax.swing.JCheckBox ckKarpetJumbo;
    private javax.swing.JCheckBox ckKarpetKecil;
    private javax.swing.JCheckBox ckKarpetSedang;
    private javax.swing.JCheckBox ckKebaya;
    private javax.swing.JCheckBox ckKeset;
    private javax.swing.JCheckBox ckRompi;
    private javax.swing.JCheckBox ckSelimutBesar;
    private javax.swing.JCheckBox ckSelimutKecil;
    private javax.swing.JCheckBox ckSepatuCat;
    private javax.swing.JCheckBox ckSepatuKulit;
    private javax.swing.JCheckBox ckSpreiBesar;
    private javax.swing.JCheckBox ckSpreiKecil;
    private javax.swing.JCheckBox ckTasBesar;
    private javax.swing.JCheckBox ckTasKecil;
    private javax.swing.JCheckBox ckTravelBag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tfBedcoverBesar;
    private javax.swing.JTextField tfBedcoverJumbo;
    private javax.swing.JTextField tfBedcoverKecil;
    private javax.swing.JTextField tfBlezer;
    private javax.swing.JTextField tfBonekaBesar;
    private javax.swing.JTextField tfBonekaJumbo;
    private javax.swing.JTextField tfBonekaKecil;
    private javax.swing.JTextField tfBonekaSedang;
    private javax.swing.JTextField tfGordenTebal;
    private javax.swing.JTextField tfGordenTipis;
    private javax.swing.JTextField tfHanduk;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfHelm;
    private javax.swing.JTextField tfJaket;
    private javax.swing.JTextField tfJas;
    private javax.swing.JTextField tfKarpetBesar;
    private javax.swing.JTextField tfKarpetJumbo;
    private javax.swing.JTextField tfKarpetKecil;
    private javax.swing.JTextField tfKarpetSedang;
    private javax.swing.JTextField tfKebaya;
    private javax.swing.JTextField tfKeset;
    private javax.swing.JTextField tfRompi;
    private javax.swing.JTextField tfSelimutBesar;
    private javax.swing.JTextField tfSelimutKecil;
    private javax.swing.JTextField tfSepatuCat;
    private javax.swing.JTextField tfSepatuKulit;
    private javax.swing.JTextField tfSpreiBesar;
    private javax.swing.JTextField tfSpreiKecil;
    private javax.swing.JTextField tfTasBesar;
    private javax.swing.JTextField tfTasKecil;
    private javax.swing.JTextField tfTravelBag;
    // End of variables declaration//GEN-END:variables
}
